// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

type Message struct {
	SessionID   string `json:"session_id"`
	Ordinal     int64  `json:"ordinal"`
	MessageID   string `json:"message_id"`
	Role        string `json:"role"`
	Model       string `json:"model"`
	StopReason  string `json:"stop_reason"`
	CreatedAt   string `json:"created_at"`
	PayloadJson []byte `json:"payload_json"`
}

type Session struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Project   string `json:"project"`
	Agent     string `json:"agent"`
	UpdatedAt string `json:"updated_at"`
}
