// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
)

const deleteMessagesForSession = `-- name: DeleteMessagesForSession :exec
DELETE FROM messages WHERE session_id = ?
`

func (q *Queries) DeleteMessagesForSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteMessagesForSession, sessionID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, title, project, agent, updated_at
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Project,
		&i.Agent,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (session_id, ordinal, message_id, role, model, stop_reason, created_at, payload_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	SessionID   string `json:"session_id"`
	Ordinal     int64  `json:"ordinal"`
	MessageID   string `json:"message_id"`
	Role        string `json:"role"`
	Model       string `json:"model"`
	StopReason  string `json:"stop_reason"`
	CreatedAt   string `json:"created_at"`
	PayloadJson []byte `json:"payload_json"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.SessionID,
		arg.Ordinal,
		arg.MessageID,
		arg.Role,
		arg.Model,
		arg.StopReason,
		arg.CreatedAt,
		arg.PayloadJson,
	)
	return err
}

const listMessages = `-- name: ListMessages :many
SELECT session_id, ordinal, message_id, role, model, stop_reason, created_at, payload_json
FROM messages
WHERE session_id = ?
ORDER BY ordinal ASC
`

func (q *Queries) ListMessages(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.SessionID,
			&i.Ordinal,
			&i.MessageID,
			&i.Role,
			&i.Model,
			&i.StopReason,
			&i.CreatedAt,
			&i.PayloadJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, title, project, agent, updated_at
FROM sessions
ORDER BY updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Project,
			&i.Agent,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (id, title, project, agent, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  title = excluded.title,
  project = excluded.project,
  agent = excluded.agent,
  updated_at = excluded.updated_at
`

type UpsertSessionParams struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Project   string `json:"project"`
	Agent     string `json:"agent"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession,
		arg.ID,
		arg.Title,
		arg.Project,
		arg.Agent,
		arg.UpdatedAt,
	)
	return err
}
